apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: yandex/clickhouse-server
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: clickhouse-stor
              mountPath: /var/lib/clickhouse/data
      volumes:
        - name: clickhouse-stor
          emptyDir: { }