kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
  sessionAffinity: None